### ISSUE TITLE
Adding option for 720p60 quality

### ISSUE THREAD

**Issue by acerbicless** [Foldex/reflex-curses#3]
Some streams I am trying to view do not have a quality of '720p' but instead use '720p60'. This causes an error when attempting to launch a stream 'error: the specified stream(s) '720p' could not be found'.
Is it possible to add '720p60' as a quality option?

**Comment by Foldex** [comment]
Streamlink allows for specifying multiple qualities to fallback on, so I added 60fps as a preferred quality, falling back to the normal version if it's not available. This should address the issue without adding a new quality specifically for 60fps, and having to play guessing games on which stream is 60 and which isn't.

**Comment by acerbicless** [comment]
Thanks
